App_Blog/urls.py
from django.urls import path
from . import views

app_name='App_Blog'


urlpatterns = [
    path('',views.BlogList.as_view(),name='blog_list'),
    path('write/',views.CreateBlog.as_view(),name='create_blog'),
    path('details/<slug:slug>',views.blog_details,name='blog_details'),
    path('liked/<pk>/',views.liked,name='liked_post'),
    path('unliked/<pk>/',views.unliked,name='unliked_post'),
    path('my-blog/',views.MyBlogs.as_view(),name='my_blogs'),
    path('edit-blog/<pk>/',views.UpdateBlog.as_view(),name='edit_blog'),
]

Home/urls.py
from django.urls import path
from Home import views
app_name='Home'

urlpatterns = [
  
  path('', views.index, name='home'),
  path('contact', views.contact, name ="contact"),
  path('faq', views.faq, name ="faq"),
  path('pcod', views.pcod, name ="pcod"),
  path('selfcare', views.selfcare, name ="selfcare"),  
]

StainStrong/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('Home.urls')),
    path('',views.index, name='index'),
    path('account/',include('App_Login.urls')),
    path('blog/',include('App_Blog.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Home/models.py
from django.db import models

# Create your models here.

Home/forms.py
from django import forms

class ContactForm(forms.Form):
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    email_address = forms.CharField(max_length=150)
    message = forms.CharField(widget= forms.Textarea, max_length=2000)

    

Home/views.py
from django.shortcuts import render,redirect
from django.views.generic import ListView
from .forms import ContactForm
from django.core.mail import message, send_mail, BadHeaderError
from django.http import HttpResponse
# Create your views here.
def index(request):
    return render(request,'Home/home.html')
def faq(request):
    return render(request,'Home/faq.html')
def pcod(request):
    return render(request,'Home/pcod.html')
def selfcare(request):
    return render(request,'Home/selfcare.html')

class home(ListView):
    template_name='Home/home.html'

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = "Website Inquiry"
            body={
                'first_name':form.cleaned_data['first_name'],
                'last_name':form.cleaned_data['last_name'],
                'email':form.cleaned_data['email'],
                'message':form.cleaned_data['message'],


            }
            message = "\n".join(body.values())
            try:
                send_mail(subject, message,'admin@example.com',['admin@example.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect("Home:home")
        
    form = ContactForm()
    return render(request, "Home/contact.html", {'form':form})

templates/Home/contact.html
{% extends 'Base.html' %}
{% load crispy_forms_tags %}
{% block title %} Contact Us {% endblock title %}
{% block body_block %}

<div class="contactmains">
	<div class="contact">
    
		<h1>Contact Me</h1>
		
			<form method="post">
				{{ form | crispy }} 
				{% csrf_token %}
				
				<button type="submit"  class="custom-btn btn-2">Contact Us</button>
	
			</form>
		
	</div>

</div>

{% endblock %}

templates/Home/faq.html
{% extends 'Base.html' %}
{% load crispy_forms_tags %}
{% load custom_filters %}
{% load static %}
{% block title %} FAQ {% endblock title %}
{% block body_block %}

<div class="faq">
    <h1>Frequently asked questions</h1>
    <div>
        <p>Let's clear our doubts regarding periods.</p>

    </div>
    <button class="accordion">Why do we call it menstruation?</button>
<div class="panel">
  <p>First up, why the heck do we call it a “menstrual” cycle anyway? Turns out, it comes from the Latin word menses, which translates to month. Ah, so it actually does make sense.</p>
</div>

<button class="accordion">Is PMS even real?</button>
<div class="panel">
  <p>If you ask any woman, including myself as a teenager who once cried when my waitress informed me that the restaurant was out of mozzarella sticks that night, PMS is most definitely real. I can count to the day when I struggle with my mood right before my period is about to start. It’s not so much that my mood changes as it is that things that wouldn’t normally upset me do. Examples include traffic, or a work mistake, or my husband’s snoring. These become insurmountable obstacles. It’s like I have less coping ability than normal.

    Alas, science has debated if PMS is a “real” phenomenon for a long time now. However, a very new study has shown that some women may simply be more sensitive to changes in hormone levels, even normal changes. These could contribute to the increased symptoms of sadness, irritability, and depression that many women face. The study also suggested that up to 56 percent of severe PMS cases are genetically inherited. Thanks, Mom.</p>


</div>

<button class="accordion">Why is my period late?</button>
<div class="panel">
  <p>There are several reasons why your period might be late.

    First of all: you might be pregnant. If you think this could be the case, you can take a home pregnancy test or see your doctor to check.
    
    However, several other factors can cause late or even missed periods, for example medication, stress, diet or exercise.
    
    In particular, young women, whose cycles are not yet so well established, often have hormonal fluctuations that can cause late or even missed periods.</p>
</div>
    
<button class="accordion">How to treat irregular periods?</button>
<div class="panel">
  <p>Indeed, if a menstrual cycle is regular, there is usually no reason for concern. Having a lower than average menstrual cycle length does not automatically mean that there is something wrong. For irregular periods there usually is also no immediate reason to consult your healthcare provider but if you are concerned, please do so. If you need contraceptionyour doctor can help you with that by prescribing you hormonal contraceptives which do not only reliably prevent unintended pregnancies but can also stabilise your menstrual cycle so that you can better plan for your periods.</p>
</div>
    
<button class="accordion">What do irregular period mean?</button>
<div class="panel">
  <p>Many women and girls suffer from irregular bleedings during their monthly menstrual cycles. Your period is irregular if it comes more frequently than 21 days, or you go 35 days or more between periods, the cycle length varies greatly. Sometimes irregular periods can be caused by some medicines, exercising too much, too low or too high body weight. Hormonal imbalancies can also cause irregular periods, e.g. thyroid hormone level abnormalities.

    Please check with your healthcare provider, who may find out the underlying reason and may be able to help you. If you also need a contraceptive, they may prescribe a hormonal one which prevents you from unintended pregnancies and may reduce your irregular bleedings.</p>
</div>
    
<button class="accordion">How long is the average period length?</button>
<div class="panel">
  <p>Bleeding can last between 2 and 7 days and can be light, heavy, short or long, because everybody is different.
    Young women and girls whose cycles are not yet so well established, often have hormonal fluctuations that can cause late or even missed periods.
    
    If you have bleeding that lasts longer than 7 days per period or is so heavy that you have to change your pad or tampon nearly every hour, you need to talk to your doctor.</p>
</div>
    
<button class="accordion">Why do have back and waist pain during the period?</button>
<div class="panel">
  <p>Heavy contractions can lead to low back pain, as the pain can radiate from the lower abdomen into the lower back. There are some hormonal contraception methods which may reduce these symptoms as they reduce your bleeding and, thus your pain as well. Please talk to your healthcare provider for individual medical advice.</p>
</div>
    
  
</div>
<script>
  var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.maxHeight) {
      panel.style.maxHeight = null;
    } else {
      panel.style.maxHeight = panel.scrollHeight + "px";
    } 
  });
}
</script>

{% endblock %}

templates/Home/home.html
{% extends 'Base.html' %}

{% load custom_filters %}
{% load static %}
{% block title %} Home {% endblock title %}

{% block body_block %}

<div class="landing-page">
    <div class="upperlanding">

        <h1> <span>Menstruated</span></h>

    </div>

    <div class="lowerlanding">
        <img src="{% static 'Home/images/14.png' %}" alt="">
    </div>

</div>
<div class="Aboutus">
    <h1>About Us</h1>
    <div class="aboutusmain">


        <div class="aboutusimg">

            <img src="{% static 'Home/images/blooddropre.png' %}" alt="">

        </div>
        <div class="aboutuscontent">

            <p>Hey strong women! Menstruated is a platform where we all unite to share our first-period stories, feelings, emotions through blogs. You can track your periods and get notified early through the mail. You should know that you are not alone in the fight against pcods by-polls. You can know the myths/facts, self-care during periods, and much much more! You go, girls.</p>

        </div>
        <div class="aboutusimg">

            <img src="{% static 'Home/images/blooddropre.png' %}" alt="">

        </div>
    </div>
</div>
<div class="reminder">
    <div class="imgrem">
        <img src="{% static 'Home/images/menstrual-calendar.jpg' %}" alt="">

    </div>
    <div class="contentrem">
        <h2>Track Your dates</h2>
        <p>Don't forget your date, Register yourself and get mails on your upcoming periods. </p>
        <a href="https://remindmemyperiods.herokuapp.com/"><button class="custom-btn btn-2">Explore</button></a>

    </div>

</div>
<div class="Blogmore">
    <h1>Explore Blogs</h1>
    <div class="blogmain">
        <div class="blogimg">
            <img src="{% static 'Home/images/18.png' %}" alt="">

        </div>
        <div class="blogcontent">

            <p>Blogs are the ways to communicate and share your thoughts. Explore how others dealt with their periods, getting stain stories, myths about periods and much more, share your experience too.</p>
            <a href="{% url 'App_Blog:blog_list' %}"><button class="custom-btn btn-2">Explore</button></a>

        </div>
        <div class="blogimg">
            <img src="{% static 'Home/images/18.png' %}" alt="">

        </div>
    </div>

</div>
<div class="ever">
    <h1>Let's talk about it</h1>
<div class="everything">

   
    <div class="card">
        <div class="card-content">
            <h2 class="card-title">FAQ's</h2>
            <p>Questions about periods, PMS and more stuff that might be a doubt to you.

            </p>
            <a href="{% url 'Home:faq' %}"><button class="custom-btn btn-2">Explore</button></a>

        </div>

    </div>
   
    <div class="card">
        <div class="card-content">
            <h2 class="card-title">PCOD/PCOS</h2>
            <p>Pcos (Polycystic Ovary Syndrome), is common among women nowadays, let's look at it in more detail.
                
                
            </p>
            <a href="{% url 'Home:pcod' %}"><button class="custom-btn btn-2">Explore</button></a>

        </div>

    </div>
   
    <div class="card">
        <div class="card-content">
            <h2 class="card-title">Self Care</h2>
            <p>“Taking care of our personal self is not a luxury but an essential need just as food and water!”
                
            </p>
            <a href="{% url 'Home:selfcare' %}"><button class="custom-btn btn-2">Explore</button></a>

        </div>

    </div>
</div>

</div>

<div class="Talkabout">
    <h1>Lets Chat</h1>
    <div class="mainchat">
        <div class="rightchat">
            <img src="{% static 'Home/images/35.png' %}" alt="">
            
    
        </div>

        <div class="leftchat">
           
            <p>
             Lets us speak to each other and discuss outspokenly whatever we feel like. Lets Chat and make everything familier and 
             nothing private that people or many girls itself are shy to speak about.
            </p>
            <a href="https://letsuschat.herokuapp.com/"><button class="custom-btn btn-2">Lets Chat</button></a>
    
        </div>
        <div class="rightchat">
            <img src="{% static 'Home/images/35.png' %}" alt="">
            
    
        </div>
       

    </div>
    
    
   

</div>
<div class="poll">
    <h1>Poll To know</h1>
    <div class="pollmain">
        <div class="pollimg">
            <img src="{% static 'Home/images/34.png' %}" alt="">
        </div>
        <div class="pollcontent">
            <p> Here is the poll section, where actually you can see the graph and results of a particular topic as many as same as you have polled and so you can also poll.</p>
            <a href="https://polledin.herokuapp.com/"><button class="custom-btn btn-2">Poll Here</button></a>
        </div>

    </div>

</div>
<div class="contacthome">
    <h1>Contact Us</h1>
    <div class="contactmain">
        <div class="contactcon">
            <p>Contact me if you find anything you want to share, either it be questions, issues or enhancements regarding this website.</p>

            <a href="{% url 'Home:contact' %}"><button class="custom-btn btn-2">Contact us</button></a>

        </div>
       <div class="contactimg">
            <img src="{% static 'Home/images/contact.png' %}" alt="">
        </div>
    </div>
</div>
<footer class="footermain">
    <div class="footerhead">
        <h1> <span>M</span>enstruated</h>
    </div>
    <div class="footermaini">
        <div class="footerimg">
            <img src="{%  static 'Home/images/24.png' %}" alt="">
        </div>
    
    
        <div class="footercontent">
           
            <p>copyright ©  2021-2023</p>
    
        </div>
    
        <div class="footerimg">
            <img src="{%  static 'Home/images/24.png' %}" alt="">
        </div>    

    </div>
        
   

  
</footer>



{% endblock %}

templates/Home/pcod.html
{% extends 'Base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %} Pcod And Pcos {% endblock title %}
{% block body_block %}
<div class="pcod">
    <h1>Pcos and Pcod</h1>
    <div>
        <p>Polycystic Ovarian Syndrome / Polycystic Ovarian Disease</p>
    </div>
    <div class="pcodm">
        <div class="pcodimg">
            <img src="{% static 'Home/images/31.jpg' %}" alt="">

        </div>
        <div class="pcodcontent">
            <h2>What is Pcod/Pcos?</h2>
            <p>Polycystic ovary syndrome (PCOS) is a condition in which the ovaries produce an abnormal amount of androgens, male sex hormones that are usually present in women in small amounts. The name polycystic ovary syndrome describes the numerous small cysts (fluid-filled sacs) that form in the ovaries. However, some women with this disorder do not have cysts, while some women without the disorder do develop cysts.

                Ovulation occurs when a mature egg is released from an ovary. This happens so it can be fertilized by a male sperm. If the egg is not fertilized, it is sent out of the body during your period.
                
                In some cases, a woman doesn’t make enough of the hormones needed to ovulate. When ovulation doesn’t happen, the ovaries can develop many small cysts. These cysts make hormones called androgens. Women with PCOS often have high levels of androgens. This can cause more problems with a woman’s menstrual cycle. And it can cause many of the symptoms of PCOS.
                
                Treatment for PCOS is often done with medication. This can’t cure PCOS, but it helps reduce symptoms and prevent some health problems.</p>

        </div>

    </div>
    <div class="detectmain">
        <div class="detectcontent">
            <h1>What causes PCOS?</h1>
            <p>The exact cause of PCOS is not clear. Many women with PCOS have insulin resistance. This means the body can't use insulin well. Insulin levels build up in the body and may cause higher androgen levels. Obesity can also increase insulin levels and make PCOS symptoms worse.

                PCOS may also run in families. It's common for sisters or a mother and daughter to have PCOS.</p>
    
        </div>
        <div class="detectimg">
            <img src="{% static 'Home/images/28.png' %}" alt="">
    
        </div>
       
    
    </div>

</div>


{% endblock %}

templates/Home/selfcare.html
{% extends 'Base.html' %}
{% load crispy_forms_tags %}
{% block title %} Self Care {% endblock title %}
{% block body_block %}
{% load static %}
<div class="selfcare">
    <h1>Self Care</h1>
    <div>
        <p>“Our cycles are a sign of our connection to humanity, the planet and all life. This is something to be honoured and seen as a blessing rather than a curse.”</p>

    </div>
    <div class="selfmain">
        <div class="selfimg">
            <img src="{% static 'Home/images/29.webp' %}" alt="">

        </div>
        <div class="selfcontent">
            <h1>Self care during periods.</h1>
            <p> Get to know yourself
                Your menstrual cycle has 4 phases, pre-ovulation, before your body releases an egg, ovulation, when the egg is released, pre-menstruation, as your body prepares to shed the lining of the uterus and menstruation when you bleed. Each phase brings new emotional and physical changes which, when we are in tune with them, can be easier to manage. Before getting into the details of exercises or thinking about changes to your diet, you can ask yourself, “how do I feel?”. Overwork, stress, lack of sleep, lack of time and space for yourself, disregard of your needs and your own inner “rhythm” of life, might disconnect us from feeling what is good for our self..</p>
                <br><br><br>

                <p>Know your body – Did you know that your cervical mucus changes during your cycle depending on your level of fertility? This is a great way to learn about the monthly changes taking place within your body. Here’s a useful article showing photos of the different kinds of mucus and when they are likely to be present in your cycle. Your body temperature also changes during your cycle. By taking your basal body temperature (BBT, your temperature upon waking) you can determine where you are in your cycle. This is often practiced as part of  natural contraception to either plan for, or to avoid pregnancy. This article explains more on BBT charting. 
                    Know your emotions – It’s become a bit of a stereotype that women get emotional during their menstrual cycle, especially in the days before menstruation (commonly known as pre-menstrual tension or PMT). There are a number of hormonal changes throughout the menstrual cycle which can drastically affect your moods! The biggest culprit is estrogen. Beginning at puberty, a woman’s ovaries start releasing estrogen in coordination with each monthly menstrual cycle. At mid-cycle, levels suddenly spike, triggering the release of an egg (ovulation). They then fall just as quickly. During the rest of the month, estrogen levels climb and fall gradually. These fluctuations can trigger changes in mood ranging from irritability and tearfulness to rage and depression. Knowing your cycle and emotions will help you and those around you to better accept and deal with these feelings, there is nothing wrong with feeling this way! Talking with your female family members or close friends can be a big help, after all I’m sure they can sympathise!
                    Adjust the rhythm of your lifestyle to your cycle – Adjust yourself to your-self! Celebrate your ebbing and flowing body and all that comes with it. If you know when your period is coming, you can better prepare by taking a relaxing bath or taking some time to yourself, you can accept the changes in mood by being gentle with yourself or requesting the understanding of those around you.
                </p>

        </div>

    </div>

</div>

{% endblock %}